### ISSUE TITLE
Inconsistent Gold Charges

### ISSUE THREAD

**Issue by laurabroder** [MHDante/Habitica-SitePass#4]
Sometimes I navigate to a blocked site and it loads without charging me gold.

**Comment by MHDante** [comment]
Do you have any examples of sites that display this behaviour?

**Comment by laurabroder** [comment]
Twitter, Facebook

**Comment by MHDante** [comment]
I can't seem to replicate the issue. I tried going to facebook and twitter and was blocked successfully... Maybe if you send me the link that lets you get through?

![image](https://cloud.githubusercontent.com/assets/4652122/17782621/7961db78-6542-11e6-8e44-daa68addb039.png)

![image](https://cloud.githubusercontent.com/assets/4652122/17782640/8a32ded4-6542-11e6-8863-99b045148ffa.png)

**Comment by laurabroder** [comment]
I re enabled the extension a couple hours ago...so far so good on both the issues I reported. (#4 and #5)

I'll circle back tomorrow, but it's likely both can be closed. Maybe the work you did on #6 corrected this, who knows?

**Comment by laurabroder** [comment]
Ok, I just navigated to Facebook.com, and I did not receive a pop-up from the extension to charge me gold.

![image](https://cloud.githubusercontent.com/assets/3170577/17784074/09f63188-6549-11e6-9e23-12d17b02abdc.png)

**Comment by laurabroder** [comment]
It worked the time after this, and then happened again just now. So yes, "inconsistent," which I do realize is the worst bug report ever. If I can figure out the pattern, I will report it.

**Comment by MHDante** [comment]
Oh! What may be happening is that you still have time remaining on your timer! Once you purchase a break, it lets you stay on this site and reload for a few minutes (Which you can set in the advanced settings).

Maybe I should add a timer! And this might fit into @UnexpectedMushroom's request in #3 

Would you mind letting me know if this is the case?
