### ISSUE TITLE
Creates several random habits

### ISSUE THREAD

**Issue by laurabroder** [MHDante/Habitica-SitePass#5]
Maybe this is expected behavior...but, it creates never random habits that say "text". I move them to the bottom of my habits list, but it either reorders them or creates additional new ones at the top.
![image](https://cloud.githubusercontent.com/assets/3170577/17215856/508d5264-54ac-11e6-97c4-6652b77504ce.png)

**Comment by MHDante** [comment]
Oh gosh. I think this has to do with the reason in #6 . I'll take a look. :(

**Comment by MHDante** [comment]
I cannot get this bug to occur on my end. Please let me know if it still occurs.
