### ISSUE TITLE
Does not work with API v3

### ISSUE THREAD

**Issue by Cantras** [MHDante/Habitica-SitePass#6]
Since API v2 has been deprecated, this extension no longer works. When attempting to access a blocked site, it will insist you don't have the gold to visit it. 

I'm hoping this can be updated. I'm behaving myself with facebook for now but I'm sure it's just a matter of time... :)

**Comment by MHDante** [comment]
Oh no! I need to look into this.... I'm fairly busy, but I'll try to take a look at it this weekend.

**Comment by MHDante** [comment]
@Cantras 

The application has been updated. (It should now say "Habitica" instead of "HabitRPG"

If you have some time, please test it and let me know if it works, so I'll close this issue.

**Comment by Cantras** [comment]
It seems to! Hurray! Thank you so much!

**Comment by Cantras** [comment]
Side note: What is your Habitica UUID? I can't promise anything, but I noticed there's no MHDante on the list of people who've gotten rewards for Habitica work and that strikes me as unfair.

**Comment by MHDante** [comment]
e5804925-e53c-48b5-90ed-03d656da0f2e

**Comment by Cantras** [comment]
There. I don't know how much you use Habitica these days, but now you have a tier for when you do. :)
