### ISSUE TITLE
Tomato.es Health Nuke

### ISSUE THREAD

**Issue by rionhunter** [MHDante/Habitica-SitePass#8]
The tomato.es habits suddenly turned on me, and I accrued negative 137 hits on the habit token thing in about an hour - Even when the tomato.es timer was active. In a little over an hour, this plug in killed my character nearly ten times.

**Comment by MHDante** [comment]
Yo, I think you have the wrong plugin! This is probably for the other dudes extension
https://github.com/HabitRPG/habitica-chrome
